---
title: "Project_1"
author: "Charles, Lei, John"
date: "2/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(leaps)
library(caret)
library(car)


#Set path to housing data.
Project <- "/Users/Chase/Desktop/MSDS/MSDS6306/Homework/SMU_MSDS_Homework/Case_Study_1/DS6372-GroupProject1/ImportedFiles/train_clean_final.csv"

HousingData <- read.csv(Project)
dim(HousingData)
Housing <- HousingData[, -c(1,7,15,73:76,79)] #Removes unnessary predictor columns from dataset
#Features removed: Id, Alley, Condition2, PoolQC, Fense, MiscFeature, MiscVal, SaleType

head(Housing)


```


```{r Train and Test Samples}
#Following code creates training and test samples. 
set.seed(1234)
index<-sample(1:dim(Housing)[1],100,replace=F)
train<-Housing[index,]
test<-Housing[-index,]

#Forward
reg.fwd=regsubsets(SalePrice~.,data=train, method = "forward", really.big = T, nvmax = 20)

coef(reg.fwd,3)

summary(reg.fwd)$adjr2
summary(reg.fwd)$rss
summary(reg.fwd)$bic


par(mfrow=c(1,3))
bics<-summary(reg.fwd)$bic
plot(1:21,bics,type="l",ylab="BIC",xlab="# of predictors")
index<-which(bics==min(bics))
points(index,bics[index],col="red",pch=10)

adjr2<-summary(reg.fwd)$adjr2
plot(1:21,adjr2,type="l",ylab="Adjusted R-squared",xlab="# of predictors")
index<-which(adjr2==max(adjr2))
points(index,adjr2[index],col="red",pch=10)

rss<-summary(reg.fwd)$rss
plot(1:21,rss,type="l",ylab="train RSS",xlab="# of predictors")
index<-which(rss==min(rss))
points(index,rss[index],col="red",pch=10)


car::vif(lm(SalePrice~HouseStyle+GrLivArea+SaleCondition,data=Housing))

housing.fwdfit<-lm(SalePrice~HouseStyle+GrLivArea+SaleCondition, data = train)

par(mfrow=c(2,2))
plot(housing.fwdfit)
```

```{r}
summary(housing.fwdfit)
```

```{r}
housing.fwdTest<-lm(SalePrice~HouseStyle+GrLivArea+SaleCondition, data = test)

par(mfrow=c(2,2))
plot(housing.fwdTest)

summary(housing.fwdTest)

```






